### ISSUE TITLE
WARNING: terminal is not fully functional

### ISSUE THREAD

**Issue by kevinslin** [danchoi/soywiki#54]
When I run the `,lp` command in Soywiki using mac vim, I get the following:

```
!git log -p WikiMain
WARNING: terminal is not fully functional
```

Get the following:
 ![wikimain____dropbox_apps_soywiki_personal_panatta__-_vim3](https://cloud.githubusercontent.com/assets/409321/6056371/c0079690-acc4-11e4-996a-df4244fe5663.jpg)

**Comment by 0robustus1** [comment]
Well technically this is a MacVim warning. MacVim needs to emulate a terminal, as it can't just use the terminal as standard vim can (as standard-vim is started from inside a terminal). It however does not provide all the features of a terminal (e.g. colors and paging), which is why the pager, which is called by git complains.

There really is no easy solution to this. We could disable paging by providing a `GIT_PAGER` environment variable and set it to `cat` for example, but as the shell-output of vim isn't scrollable this is not very useful either. The only way to solve this would be to create a temporary buffer and read the shell output into this buffer. But i'm not entirely sure if we want to support this.

**Comment by 0robustus1** [comment]
For now we do not want to implement this.
